### ISSUE TITLE
Gräns för statlig inkomstskatt

### ISSUE THREAD

**Issue by twogood** [tomasbjerre/starta-eget-konsultbolag#1]
Gränsen för statlig skatt från 2019 är 490 700 kr/år, alltså cirka 40891 kr/månad

Källa:

https://www.skatteverket.se/privat/etjansterochblanketter/svarpavanligafragor/inkomstavtjanst/privattjansteinkomsterfaq/narskamanbetalastatliginkomstskattochhurhogarden.5.10010ec103545f243e8000166.html

**Comment by tomasbjerre** [comment]
Fixat!
